import { api } from './index';
import type { Habit } from './types';
import type { CreateHabit, Snapshot } from '../../shared/api';
export const getHabits = () => api<Habit[]>('/habits');
export const createHabit = async (data: CreateHabit) => (await api<{id:string}>('/habits', 'POST', data)).id;
export const deleteHabit = (id: string) => api(`/habits/${id}`, 'DELETE');
export const finishHabit = (id: string) => api(`/habits/${id}/finished`, 'PUT', {finished: true});
export const reopenHabit = (id: string) => api(`/habits/${id}/finished`, 'PUT', {finished: false});
export const setHabitLog = (id: string, date: string, checked: boolean) => api(`/habits/${id}/check-ins/${date}`, 'PUT', {checked});
export const getHabitLogs = async (id: string, since: string) => (await api<Snapshot>('/state')).habitLogs.filter(l => l.habit_id === id && l.logged_date >= since);
